### ISSUE TITLE
Failed to activate the linter-python package

### ISSUE THREAD

**Issue by sebastianczech** [pchomik/linter-python#51]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [linter-python](https://github.com/pchomik/linter-python) package 3.1.2

### Stack Trace

Failed to activate the linter-python package

```
At Cannot find module 'tmp'

Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-python/node_modules/atom-linter/lib/helpers.js:22:12)
    at /packages/linter-python/node_modules/atom-linter/lib/helpers.js:105:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-python/node_modules/atom-linter/lib/index.js:140:16)
    at /packages/linter-python/node_modules/atom-linter/lib/index.js:327:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-python/lib/parser.js:12:18)
    at /packages/linter-python/lib/parser.js:120:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-python-run 0.9.3 
atom-typescript 11.0.10 
autoclose-html 0.23.0 
autocomplete-modules 1.8.0 
autocomplete-python 1.10.3 
autocomplete-wordpress-hooks 0.2.3 
busy-signal 1.4.3 
compare-files 0.8.1 
es6-javascript 1.0.0 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-python 3.1.2 
linter-ui-default 1.6.10 
open-recent 5.0.0 
pigments 0.40.2 
pretty-json 1.6.4 
python-debugger 0.2.0 
python-tools 0.6.9 
seti-icons 1.5.4 
todo-show 2.1.0 
turbo-javascript 1.4.0 
wordpress-api 1.2.2 
```

**Comment by joeashcraft** [comment]
I got this error today after migrating workstations, and was able to resolve it with the steps in https://github.com/pchomik/linter-python/pull/20#issuecomment-217813339 
in my case, `apm link` did nothing as the files already exist, but `apm install` seems to fix things

I ran...
```bash
cd ~/.atom/packages
for dd in */; do
  cd $dd
  apm link
  apm install
  cd ..
done
```
